Solution.Examples/DataAccess/MyShop.Web/Models/CreateOrderModel.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyShop.Web.Models
{
    public class CreateOrderModel
    {
        public IEnumerable<LineItemModel> LineItems { get; set; }

        public CustomerModel Customer { get; set; }
    }
}

Solution.Examples/DataAccess/MyShop.Web/Models/CustomerModel.cs
namespace MyShop.Web.Models
{
    public class CustomerModel
    {
        public string Name { get; set; }
        public string ShippingAddress { get; set; }
        public string City { get; set; }
        public string PostalCode { get; set; }
        public string Country { get; set; }
    }
}

Solution.Examples/DataAccess/MyShop.Web/Models/ErrorViewModel.cs
using System;

namespace MyShop.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Solution.Examples/DataAccess/MyShop.Web/Models/LineItemModel.cs
using System;

namespace MyShop.Web.Models
{
    public class LineItemModel
    {
        public Guid ProductId { get; set; }
        public int Quantity { get; set; }
    }
}

Solution.Examples/DataAccess/MyShop.Web/Controllers/CustomerController.cs
using Microsoft.AspNetCore.Mvc;
using MyShop.Domain.Models;
using MyShop.Infrastructure.Repositories;

namespace MyShop.Web.Controllers
{
    public class CustomerController : Controller
    {
        private readonly IRepository<Customer> _customerRepository;

        public CustomerController(IRepository<Customer>  customerRepository )
        {
            _customerRepository = customerRepository;
        }

        public IActionResult Index(Guid? id)
        {
            if (id == null)
            {
                var customers = _customerRepository.All();

                return View(customers);
            }
            else
            {
                var customer = _customerRepository.Get(id);

                return View(new[] { customer });
            }
        }
    }
}

Solution.Examples/DataAccess/MyShop.Web/Controllers/OrderController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using MyShop.Domain.Models;
using MyShop.Infrastructure.Repositories;
using MyShop.Web.Models;

namespace MyShop.Web.Controllers
{
    public class OrderController : Controller
    {
        private readonly IOrderCreationUnitOfWorkRepo _repository;

        //private readonly IRepository<Order> _orderRepository;
        //private readonly IRepository<Product> _productRepository;
        //private readonly IRepository<Customer> _customerRepository;

        public OrderController(IOrderCreationUnitOfWorkRepo repository)
        {
             _repository = repository;
            //_orderRepository = orderRepository;
            //_productRepository = productRepository;
            //_customerRepository = customerRepository;
        }

        public IActionResult Index()
        {
            var orderRepo = _repository.OrderRepository;
            var orders = orderRepo.Find(o => o.OrderDate > DateTime.UtcNow.AddDays(-1));
            return View(orders);
        }

        public IActionResult Create()
        {
            var productRepo = _repository.ProductRepository;
            var products = productRepo.All();
            return View(products);
        }

        [HttpPost]
        public IActionResult Create(CreateOrderModel model)
        {
            if (!model.LineItems.Any()) return BadRequest("Please submit line items");

            if (string.IsNullOrWhiteSpace(model.Customer.Name)) return BadRequest("Customer needs a name");

            var orderRepo = _repository.OrderRepository;
            var customerRepo = _repository.CustomerRepository;

            var customer = customerRepo
                  .Find(c => c.Name ==  model.Customer.Name)
                  .FirstOrDefault();
            if(customer != null)
            {
                customer.Name = model.Customer.Name;
                customer.ShippingAddress = model.Customer.ShippingAddress;
                customer.PostalCode = model.Customer.PostalCode;
                customer.City = model.Customer.City;
                customer.Country = model.Customer.Country;

                customerRepo.Update(customer);
            }
            else
            {
                 customer = new Customer
                {
                    Name = model.Customer.Name,
                    ShippingAddress = model.Customer.ShippingAddress,
                    City = model.Customer.City,
                    PostalCode = model.Customer.PostalCode,
                    Country = model.Customer.Country
                };
                customerRepo.Add(customer);
            }
         
            var order = new Order
            {
                LineItems = model.LineItems
                    .Select(line => new LineItem { ProductId = line.ProductId, Quantity = line.Quantity })
                    .ToList(),

                Customer = customer
            };
            orderRepo.Add(order);
            _repository.SaveChanges();
            return Ok("Order Created");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Solution.Examples/DataAccess/MyShop.Web/Views/Customer/Index.cshtml
@model IEnumerable<MyShop.Domain.Models.Customer>

@{
    ViewData["Title"] = "All customers";
}

<h1>Customers</h1>

@foreach (var customer in Model)
{
    <div class="row mb-lg-5">
        <div class="col-lg-8">
            <h4 class="d-flex justify-content-between align-items-center mb-3">
                <span class="text-muted">Customer </span>
                <span class="badge badge-secondary badge-pill">@customer.Name</span>
            </h4>
            <img src="data:image/jpeg;base64,@System.Text.Encoding.Default.GetString(customer.ProfilePicture)" width="200" />
            <div>
                <p>@customer.ShippingAddress</p>
                <p>@customer.City</p>
                <p>@customer.PostalCode</p>
                <p>@customer.Country</p>
            </div>
            <a href="/Customer/Index/@customer.CustomerId">More details</a>
        </div>
    </div>
}

Solution.Examples/DataAccess/MyShop.Web/Views/Order/Create.cshtml
@model IEnumerable<MyShop.Domain.Models.Product>

@{
    ViewData["Title"] = "Create a new order";
}

<h1>Create a new order</h1>
<div class="row">
    <div class="col-4">
        <strong>Add items to order</strong>
        <div class="form-row mb-lg-5">
            <div class="col">
                <label>Select product</label>
                <select v-model="selectedProduct" class="form-control" id="product">
                    <option disabled value="">Please select one</option>
                    @foreach (var product in Model)
                    {
                        <option value="@product.ProductId"
                                v-bind:value="{ productId: '@product.ProductId', name: '@product.Name', price: @product.Price.ToString(System.Globalization.CultureInfo.InvariantCulture) }">
                            @product.Name
                        </option>
                    }
                </select>
            </div>
            <div class="col">
                <label>Quantity</label>
                <input v-model="selectedQuantity" class="form-control" id="quantity" type="number" value="1" />
            </div>
        </div>
        <button v-on:click="add" :disabled='canAddToOrder' class="btn btn-outline-success">Add to order</button>
    </div>
    <div class="col-4">
        <strong>Current order</strong>
        <div class="mb-lg-5">
            <div class="mb-lg-5">
                Items
                <ul class="list-group">
                    <li v-for="line in lineItems" :key="product.productId" class="list-group-item d-flex justify-content-between lh-condensed">
                        <div>
                            <h6 class="my-0">{{ line.product.name }}</h6>
                            <small class="text-muted">Quantity: {{ line.quantity }}</small>
                        </div>
                        <span class="text-muted">${{ line.product.price *  line.quantity }}</span>
                    </li>

                    <li class="list-group-item d-flex justify-content-between">
                        <span>Total (USD)</span>
                        <strong>${{ totalPrice }}</strong>
                    </li>
                </ul>
            </div>
            <div>
                Customer details
                <div class="form-group mb-lg-5">
                    <div class="form-group">
                        <input v-model="fullname" placeholder="Customer name" class="form-control">
                    </div>
                    <div class="form-group">
                        <input v-model="shippingAddress" placeholder="Customer address" class="form-control">
                    </div>
                    <div class="form-group">
                        <input v-model="city" placeholder="Gothenburg" class="form-control">
                    </div>
                    <div class="form-group">
                        <input v-model="postalCode" placeholder="### ##" class="form-control">
                    </div>
                    <div class="form-group">
                        <input v-model="country" placeholder="Sweden" class="form-control">
                    </div>
                </div>
            </div>
            <button v-on:click="submit" :disabled='canSubmitOrder' class="btn btn-success">CREATE ORDER</button>
        </div>
    </div>
</div>

<div id="orderSuccess" class="modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Order Creation</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                
            </div>
        </div>
    </div>
</div>

@section Scripts
{
    <script type="text/javascript">
            var app = new Vue({
                el: '#app',
                data: {
                    fullname: null,
                    shippingAddress: null,
                    city: null,
                    postalCode: null,
                    country: null,

                    selectedProduct: '',
                    selectedQuantity: 1,
                    totalPrice: 0,
                    lineItems: new Array()
                },
                computed: {
                    canSubmitOrder: function () {
                        return this.lineItems.length == 0 || this.fullname == null
                    },
                    canAddToOrder: function () {
                        return this.selectedProduct == ''
                    }
                },
                methods: {
                    add: function () {
                        var lineItem = {
                            product: this.selectedProduct,
                            quantity: this.selectedQuantity
                        }

                        if (product == null) return

                        this.lineItems.push(lineItem)

                        this.totalPrice += lineItem.product.price * lineItem.quantity
                    },
                    submit: function () {
                        var data = {
                            customer: {
                                name: this.fullname,
                                shippingAddress: this.shippingAddress,
                                city: this.city,
                                postalCode: this.postalCode,
                                country: this.country
                            },
                            lineItems: this.lineItems.map(function (line) {
                                return {
                                    productId: line.product.productId,
                                    quantity: line.quantity
                                }
                            })
                        }

                        $.ajax({
                            url: "/Order/Create",
                            data: data,
                            type: 'post',
                            error: function (XMLHttpRequest, textStatus, errorThrown) {
                                $(".modal-body").html("<strong>ERROR</strong><p>" + XMLHttpRequest.responseText + "</p>")
                                $('#orderSuccess').modal('show')
                            },
                            success: function (data) {
                                $(".modal-body").html("<strong>Success!</strong><p>The order was successfully created</p>")
                                $('#orderSuccess').modal('show')
                            }
                        });
                    }
                }
            })
    </script>
}

Solution.Examples/DataAccess/MyShop.Web/Views/Order/Index.cshtml
@model IEnumerable<MyShop.Domain.Models.Order>

@{
    ViewData["Title"] = "All orders";
}

<h1>Orders</h1>

@foreach (var order in Model)
{
    <div class="row mb-lg-5">
        <div class="col-lg-8">
            <h4 class="d-flex justify-content-between align-items-center mb-3">
                <span class="text-muted">Order #</span>
                <span class="badge badge-secondary badge-pill">@order.OrderId</span>
            </h4>
            <ul class="list-group">
                @foreach (var item in order.LineItems)
                {
                    <li class="list-group-item d-flex justify-content-between lh-condensed">
                        <div>
                            <h6 class="my-0">@item.Product.Name</h6>
                            <small class="text-muted">Quantity: @item.Quantity</small>
                        </div>
                        <span class="text-muted">$@(item.Product.Price * item.Quantity)</span>
                    </li>
                }

                <li class="list-group-item d-flex justify-content-between">
                    <span>Total (USD)</span>
                    <strong>$@order.OrderTotal</strong>
                </li>
            </ul>
        </div>
    </div>
}

Solution.Examples/DataAccess/MyShop.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyShop.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Order" asp-action="Index">MyShop.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="Index">Orders</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="Index">Customers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="Create">Create new order</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div id="app" class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - MyShop.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/vue@2.6.14"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>